Vagrant::Config.run do |config|
	config.vm.define :db do |node_1|
		node_1.vm.box = "precise64"
		node_1.vm.network :hostonly, "172.18.0.2"
		node_1.vm.customize [ "modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "database-server" ]
		node_1.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "test::users"
			chef.json.merge!({
				:run_list => [ "recipe[test::users]", "recipe[test::localapt]", "recipe[test::installmysql]" ],
			})
		end
	end
	config.vm.define :ws do |node_2|
		node_2.vm.box = "precise32"
		node_2.vm.network :hostonly, "172.18.0.3"
		node_2.vm.customize [ "modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "web-server" ]
		node_2.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "test::users"
			chef.json.merge!({
				:run_list => [ "recipe[test::users]", "recipe[test::localapt]", "recipe[test::installapache2]" ],
			})
		end
	end
end
