# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.5"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm .define :hadoopmaster do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--memory", 300, "--cpus", 2, "--name", "hadoopmaster",  "--natdnshostresolver1", "on" ]
		end
	end
	config.vm .define :hadoopslave01 do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--memory", 300, "--cpus", 2, "--name", "hadoopslave01",  "--natdnshostresolver1", "on" ]
		end
	end
	config.vm .define :hadoopslave02 do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--memory", 300, "--cpus", 2, "--name", "hadoopslave02",  "--natdnshostresolver1", "on" ]
		end
	end
	config.vm .define :hadoopslave03 do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--memory", 300, "--cpus", 2, "--name", "hadoopslave03",  "--natdnshostresolver1", "on" ]
		end
	end
	config.vm .define :hadoopslave04 do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize ["modifyvm", :id, "--memory", 300, "--cpus", 2, "--name", "hadoopslave04",  "--natdnshostresolver1", "on" ]
		end
	end
end
