# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.5"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define :master do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
    			vb.customize [ "modifyvm", :id, "--memory", 512, "--name", "pj-master-monki", "--cpus", 2 ]
  		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::java-64]", "recipe[test::hostname]", "recipe[test::pj]", "recipe[test::rsakeys-ms]", "recipe[test::clustercode-ms]" ],
				:host_name => "pj-master.cluster.org",
			})
		end
	end
	config.vm.define :pj1 do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
    			vb.customize [ "modifyvm", :id, "--memory", 896, "--name", "pj-wn1-monki", "--cpus", 2 ]
  		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::java-64]", "recipe[test::hostname]", "recipe[test::pj]", "recipe[test::rsakeys-wn]" ],
				:host_name => "pj-wn1.cluster.org",
			})
		end
	end
	config.vm.define :pj2 do |node|
		node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
    			vb.customize [ "modifyvm", :id, "--memory", 896, "--name", "pj-wn2-monki", "--cpus", 2 ]
  		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::java-64]", "recipe[test::hostname]", "recipe[test::pj]", "recipe[test::rsakeys-wn]" ],
				:host_name => "pj-wn2.cluster.org",
			})
		end
	end
	config.vm.define :pj3 do |node|
                node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
                node.vm.provider "virtualbox" do |vb|
    			vb.customize [ "modifyvm", :id, "--memory", 896, "--name", "pj-wn3-monki", "--cpus", 2 ]
  		end
                node.vm.provision :chef_solo do |chef|
                        chef.cookbooks_path = "cookbooks"
                        chef.json.merge!({
                                :run_list => [ "recipe[test::java-64]", "recipe[test::hostname]", "recipe[test::pj]", "recipe[test::rsakeys-wn]" ],
                                :host_name => "pj-wn3.cluster.org",
                        })
                end
        end
	config.vm.define :pj4 do |node|
                node.vm.box = "precise64"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
                node.vm.provider "virtualbox" do |vb|
    			vb.customize [ "modifyvm", :id, "--memory", 896, "--name", "pj-wn4-monki", "--cpus", 2 ]
  		end
                node.vm.provision :chef_solo do |chef|
                        chef.cookbooks_path = "cookbooks"
                        chef.json.merge!({
                                :run_list => [ "recipe[test::java-64]", "recipe[test::hostname]", "recipe[test::pj]", "recipe[test::rsakeys-wn]" ],
                                :host_name => "pj-wn4.cluster.org",
                        })
                end
        end
end
