#!/usr/bin/expect

	set username    ""
        set host        ""
        set pass        ""
        set location    ""
        set phrase     	""
	set sizeargv	[llength $argv]

if { $sizeargv == 2 || $sizeargv == 4 || $sizeargv == 6 || $sizeargv == 8 || $sizeargv == 10 } {
	for {set i 0} {$i < [llength $argv]} {incr i 2} {
        	set argvtmp [lindex $argv $i];
	        if {$argvtmp == "-u"} { #username
                	set index [expr $i+1];
        	        set username [lindex $argv $index];
	        } elseif {$argvtmp == "-p"} {#pass
                	set index  [expr $i+1];
        	        set pass  [lindex $argv $index];
	        } elseif {$argvtmp == "-f"} {#phrase
                	set index  [expr $i+1];
        	        set phrase [lindex $argv $index];
	        } elseif {$argvtmp == "-h"} {#host
                	set index  [expr $i+1];
        	        set host  [lindex $argv $index];
	        } elseif {$argvtmp == "-l"} {#location
	                set index  [expr $i+1];
                	set location  [lindex $argv $index];
        	}
	}
} else {
	send_user "Error parametros incompletos\n"
        send_user "Uso: configssh -u username -p pass -f phrase -h host -l location\n"
        exit 1
}


spawn ssh-keygen -t rsa

expect "*.ssh/id_rsa):" {send "$location\r"}

expect {
	"Overwrite (y/n)?" {send "y\r"; exp_continue}
	"*(empty for no passphrase):" {send "$phrase\r"}
	}
expect "*passphrase again:" {send "$phrase\r"}


expect "*.ssh/id_rsa.pub."
#send "exit\r"
send_user "realizado"
