# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.5"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define :master, :primary => true do |node|
		node.vm.box = "lucid32"
		#node.vm.network "private_network", ip: "10.0.0.2"
		node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 512, "--cpus", 2, "--name", "master" ]
		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[crack::preinstall]",
				"recipe[crack::hostname]",
				"recipe[crack::user]",
				"recipe[crack::mpichconfigureserver]",
				"recipe[crack::installjohn]" ],
				:host_name => "master.cluster.org"
			})
		end
	end

	config.vm.define :wn1 do |node|
		node.vm.box = "lucid32"
		#node.vm.network "private_network", ip: "10.0.0.3"
                node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
		node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 512, "--cpus", 2, "--name", "worker1"]
                end
		node.vm.provision :chef_solo do |chef|
                        chef.cookbooks_path = "cookbooks"
                        chef.json.merge!({
                                :run_list => [ "recipe[crack::preinstall]" , 
                                "recipe[crack::hostname]",
                                "recipe[crack::user]",
                                "recipe[crack::mpichconfigureserver]",
                                "recipe[crack::installjohn]" ],
				:host_name => "wn1.cluster.org"
                        })
                end
	end

	config.vm.define :wn2 do |node|
                node.vm.box = "lucid32"
                #node.vm.network "private_network", ip: "10.0.0.4"
                node.vm.network "public_network", bridge: "wlan0" #"eth0" #quitar bridge para que vagrant pregunte cual interfaz utilizar
                node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 512, "--cpus", 2, "--name", "worker2" ]
                end
		node.vm.provision :chef_solo do |chef|
                        chef.cookbooks_path = "cookbooks"
                        chef.json.merge!({
                                :run_list => [ "recipe[crack::preinstall]",
                                "recipe[crack::hostname]",
                                "recipe[crack::user]",
                                "recipe[crack::mpichconfigureserver]",
                                "recipe[crack::installjohn]" ],
				:host_name => "wn2.cluster.org"
                        })
                end
        end
end
