# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.define :wn1 do |node|
		node.vm.box = "precise64"
    node.vm.network :bridged, :bridge => "eth0"
		node.vm.customize [ "modifyvm", :id, "--memory", 325, "--cpus", 1, "--name", "worker1" ]
                node.vm.provision :chef_solo do |chef|
                        chef.cookbooks_path = "cookbooks"
                        chef.add_recipe "confighost::preinstall"
                        chef.json.merge!({
																:run_list => [ "recipe[confighost::preinstall]" , "recipe[confighost::hostname]" , "recipe[confighost::hostconfigurenode]" ],
																:host_name => "wn1.cluster.org" ,
																:alias => "wn1" ,
																:ip_maquina_local => "172.17.9.15" ,#representa la ip de la maquina host donde corren las vm o donde se guarden los archivos temporales
																:pass_maquina_local => "0832294-3743" ,#el pass de la maquina
																:user_maquina_local => "monki" ,# el usuario de la manquina
																:path_project_vagrant => "/home/monki/recipes/plataformas/autoHosts/cookbooks/confighost/files/default"#el path donde se guardan los temporales
                        })
                end
	end
	
	config.vm.define :wn2 do |node|
		node.vm.box = "centos64"
    node.vm.network :bridged, :bridge => "eth0"
		node.vm.customize [ "modifyvm", :id, "--memory", 325, "--cpus", 1, "--name", "worker2" ]
                node.vm.provision :chef_solo do |chef|
                        chef.cookbooks_path = "cookbooks"
                        chef.add_recipe "confighost::preinstall"
                        chef.json.merge!({
																:run_list => [ "recipe[confighost::preinstall]" , "recipe[confighost::hostname]" , "recipe[confighost::hostconfigurenode]" ],
																:host_name => "wn2.cluster.org" ,
																:alias => "wn2" ,
																:ip_maquina_local => "172.17.9.15" ,
																:pass_maquina_local => "0832294-3743" ,
																:user_maquina_local => "monki" ,
																:path_project_vagrant => "/home/monki/recipes/plataformas/autoHosts/cookbooks/confighost/files/default"
                        })
                end
	end

	config.vm.define :master, :primary => true do |node_1|
		node_1.vm.box = "centos64"
		node_1.vm.network :bridged, :bridge => "eth0"
		node_1.vm.customize [ "modifyvm", :id, "--memory", 325, "--cpus", 1, "--name", "master" ]
		node_1.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "confighost::preinstall"
			chef.json.merge!({
				:run_list => [ "recipe[confighost::preinstall]" , "recipe[confighost::hostname]" , "recipe[confighost::hostconfiguremaster]" ],
				:host_name => "master.cluster.org" ,
				:hostslaves => ["wn1" , "wn2"],
				:alias => "master" ,
				:ip_host_machine => "172.17.9.15"  #representa la ip de la maquina host donde corren las vm o donde se guarden los archivos temporales
			})
		end
	end
end
