# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
	config.vm.define :wn1 do |node|
		node.vm.box = "precise64"
    node.vm.network :bridged, :bridge => "eth0"
		node.vm.customize [ "modifyvm", :id, "--memory", 325, "--cpus", 1, "--name", "worker1" ]
		node.vm.provision :chef_solo do |chef|
		  chef.cookbooks_path = "cookbooks"
		  chef.add_recipe "confighost::preinstall"
		  chef.json.merge!({
		            :run_list => [ "recipe[confighost::preinstall]" , "recipe[confighost::hostname]" , "recipe[confighost::hostconfigurenode]" ],
																:host_name => "wn1.cluster.org" ,
																:alias => "wn1"
                        })
      end
	end
	
	config.vm.define :wn2 do |node|
		node.vm.box = "centos64"
    node.vm.network :bridged, :bridge => "eth0"
		node.vm.customize [ "modifyvm", :id, "--memory", 325, "--cpus", 1, "--name", "worker2" ]
    node.vm.provision :chef_solo do |chef|
		  chef.cookbooks_path = "cookbooks"
		  chef.add_recipe "confighost::preinstall"
		  chef.json.merge!({
		            :run_list => [ "recipe[confighost::preinstall]" , "recipe[confighost::hostname]" , "recipe[confighost::hostconfigurenode]" ],
																:host_name => "wn2.cluster.org" ,
																:alias => "wn2"																
                        })
      end
	end

	config.vm.define :master, :primary => true do |node_1|
		node_1.vm.box = "precise64"
		node_1.vm.network :bridged, :bridge => "eth0"
		node_1.vm.customize [ "modifyvm", :id, "--memory", 325, "--cpus", 1, "--name", "master" ]
		node_1.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "confighost::preinstall"
			chef.json.merge!({
				:run_list => [ "recipe[confighost::preinstall]" , "recipe[confighost::hostname]" , "recipe[confighost::hostconfiguremaster]" ],
				:host_name => "master.cluster.org" ,				
				:alias => "master" ,
				:hostslaves => ["wn1", "wn2" ]#lista de todos los nodos
			})
		end
	end
end
