# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.5"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define :loadb01 do |node|
		node.vm.box = "base"
		node.vm.network "private_network", ip: "172.168.0.100"
		node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 512, "--cpus", 1, "--name", "loadb01" ]
		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::installhaproxy]" ]
			})
		end
	end
	config.vm.define :web01 do |node|
		node.vm.box = "base"
		node.vm.network "private_network", ip: "172.168.0.2"
		node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 300, "--cpus", 1, "--name", "web01" ]
		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::installapache2]",
				"recipe[test::page1]" ]
			})
		end
	end
	config.vm.define :web02 do |node|
		node.vm.box = "base"
		node.vm.network "private_network", ip: "172.168.0.3"
		node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 300, "--cpus", 1, "--name", "web02" ]
		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::installapache2]",
				"recipe[test::page2]" ]
			})
		end
	end
	config.vm.define :web03 do |node|
		node.vm.box = "base"
		node.vm.network "private_network", ip: "172.168.0.4"
		node.vm.provider "virtualbox" do |vb|
			vb.customize [ "modifyvm", :id, "--memory", 300, "--cpus", 1, "--name", "web03" ]
		end
		node.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.json.merge!({
				:run_list => [ "recipe[test::installapache2]",
				"recipe[test::page3]" ]
			})
		end
	end
end
