#!/bin/sh
cd /tmp
if [ ! -f run_1st_as_myproxy ]; then
   wget http://globus.org/toolkit/docs/5.2/5.2.0/admin/quickstart/run_1st_as_myproxy
fi
if [ ! -f run_2nd_as_root ]; then
   wget http://globus.org/toolkit/docs/5.2/5.2.0/admin/quickstart/run_2nd_as_root
fi
if [ ! -f run_3rd_as_myproxy ]; then
   wget http://globus.org/toolkit/docs/5.2/5.2.0/admin/quickstart/run_3rd_as_myproxy
fi

sudo -H -E -u myproxy perl run_1st_as_myproxy $1
sudo perl run_2nd_as_root
sudo -H -E -u myproxy perl run_3rd_as_myproxy $1
